### ISSUE TITLE
[3.4b3] Groupings are not grouped

### ISSUE THREAD

**Issue by xiaohutai** [bolt/bolt#7096]
Records in an overview (e.g. Pages listing) with a `grouping` taxonomy are not grouped like earlier versions.

Details
-------

 - Relevant Bolt Version: [ 3.4.0-beta3 ]
 - Install type: [ Zip/tarball install ]
 - PHP version: [ 5.6 ]
 - Used web server: [ Apache/2.2.22 (Debian) ]

Reproduction
------------

- Install Bolt
- Add some dummy content
- Go to `/bolt/overview/pages`

**Comment by GawainLynch** [comment]
Fixed in #7099

**Comment by xiaohutai** [comment]
Hi @GawainLynch ,
This is a different issue. This issue concerns grouping of contenttypes with a `grouping` (chapters) taxonomy (in listings).

The PR you linked is a (new) feature for named repeaters.

**Comment by GawainLynch** [comment]
@xiaohutai this is 3.4-HEAD for me, with Pages sorting but taxonomy:
![screenshot from 2017-10-18 10-32-27](https://user-images.githubusercontent.com/1427081/31708572-aa361460-b3ef-11e7-829d-15b59a81397c.png)

**Comment by xiaohutai** [comment]
@GawainLynch 😮 

I still have the issue on 3.4/HEAD

I spammed the Prefill database, so I have 30 items on one page:

![groupings](https://user-images.githubusercontent.com/4630335/31710900-af49dcf0-b3f6-11e7-907e-5b68fb97ddd6.png)

**Comment by bobdenotter** [comment]
Looking at the screenshots you both posted: They _are_ grouping, but they seem to be _sorted_ on the id.

**Comment by GawainLynch** [comment]
Haha … At least someone is paying attention today! :+1:

**Comment by GawainLynch** [comment]
Take 2 … Fixed in #7131
